---
driver_plugin: vagrant
driver_config:
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_solo

platforms:
- name: centos-6.7
  driver_config:
    box: opscode-centos-6.7
- name: centos-7.0
  driver_config:
    box: opscode-centos-7.0
- name: rhel-6.5
  driver_config:
    box: local-rhel-6.5
    box_url: file://<%= File.expand_path('~') %>/opscode_rhel-6.5_chef-provisionerless.box
- name: rhel-7.0
  driver_config:
    box: local-rhel-7.0
    box_url: file://<%= File.expand_path('~') %>/opscode_rhel-7.0_chef-provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[machine_tag]
  - recipe[fake]
- name: create
  run_list:
  - recipe[machine_tag]
  - recipe[fake::create_tags]
  attributes:
    cloud:
      provider: vagrant
- name: delete
  run_list:
  - recipe[machine_tag]
  - recipe[fake::create_tags]
  - recipe[fake::delete_tags]
  attributes:
    cloud:
      provider: vagrant
- name: list
  run_list:
  - recipe[machine_tag]
  - recipe[fake::create_tags]
  - recipe[fake::list_tags]
  attributes:
    cloud:
      provider: vagrant
  provisioner:
    solo_rb:
      log_location: /var/log/chef-solo.log
- name: search
  run_list:
  - recipe[machine_tag]
  - recipe[fake::create_tags]
  - recipe[fake::search_tags]
  attributes:
    cloud:
      provider: vagrant
  provisioner:
    solo_rb:
      log_location: /var/log/chef-solo.log
