---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  log_file: /var/log/chef-solo.log

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list: ["recipe[machine_tag::default]"]

- name: create
  run_list: ["recipe[fake::create_tags]"]
  attributes:
    cloud:
      provider: vagrant

- name: delete
  run_list: ["recipe[fake::create_tags]", "recipe[fake::delete_tags]"]
  attributes:
    cloud:
      provider: vagrant

- name: list
  run_list: ["recipe[fake::create_tags]", "recipe[fake::list_tags]"]
  attributes:
    cloud:
      provider: vagrant

- name: search
  run_list: ["recipe[fake::create_tags]", "recipe[fake::search_tags]"]
  attributes:
    cloud:
      provider: vagrant
