---
driver_plugin: vagrant
driver_config:
  use_vagrant_provision: true
  use_vagrant_berkshelf_plugin: true
  require_chef_omnibus: true
  use_vagrant_bindler_plugin: true
  log_file: /var/log/chef-solo.log

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: create
  run_list: ["recipe[fake::create_tag]"]
  attributes: {}

- name: delete
  run_list: ["recipe[fake::delete_tag]"]
