language: ruby
rvm:
- 2.3.1
before_install:
- curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.0.3
- gem install bundler -v 1.11.2
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout master
  - git checkout -qf $TRAVIS_COMMIT
  - chef exec bundle install --jobs=3 --retry=3
before_script: chef exec rake setup_test_environment
script: chef exec rake except_kitchen
notifications:
  slack:
    secure: O3w/D2xUxgWwKY6aRiLP0KvRnUDXS7t9bGzQELo+d6KxGXRhf3mo32FeKKI2MdIVnZJf+nV+/5eIskH7VtcaW+EgS71npLs4NQBrqM5TR3J0gkRoYXGvH8f7VgXtHc3NbrHwc2eCLsacEam4BFHlJQqACRfWLbnS/186gEoLb3o=
